version: '3'

services:

  gitlab:
    image: gitlab/gitlab-ce
    restart: unless-stopped
    hostname: gitlab
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    ports:
      - 10080:80
      - 10443:443
      - 10022:22

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
